Vagrant.configure("2") do |config|
  config.vm.define :haproxyUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.provision "shell", path: "script.sh"
    servidorUbuntu.vm.hostname = "haproxyUbuntu"
  end
  config.vm.define :web1Ubuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.4"
    servidorUbuntu.vm.provision "shell", path: "script.sh"
    servidorUbuntu.vm.hostname = "web1Ubuntu"
  end
  config.vm.define :web2Ubuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.5"
    servidorUbuntu.vm.provision "shell", path: "script.sh"
    servidorUbuntu.vm.hostname = "web2Ubuntu"
  end
end
