# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :vagrantVM1 do |vagrantVM1|
    vagrantVM1.vm.box = "bento/ubuntu-20.04"
    vagrantVM1.vm.provision :shell, path: "provisioner_haproxy.sh"
    vagrantVM1.vm.network :private_network, ip: "192.168.100.4"
    vagrantVM1.vm.hostname = "vagrantVM1"
  end

  MACHINE = 3
  (2..MACHINE).each do |i|
    config.vm.define "vagrantVM#{i}" do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.provision "shell" do |s|
       s.path = "provisioner_backend.sh"
       s.args = ["#{i}"]
    end
    node.vm.network :private_network, ip: "192.168.100.#{i}"
    node.vm.hostname = "vagrantVM#{i}"
    end
  end

end
