#!/bin/bash

# Function app and storage account names must be unique.
storageName=classifstoragegus
functionAppName=ClassifyFuncApp
region=centralus
pythonVersion=3.7

echo "Create a resource group."
az group create --name myResourceGroup --location $region

echo "Create an Azure storage account in the resource group."
az storage account create \
  --name $storageName \
  --location $region \
  --resource-group myResourceGroup \
  --sku Standard_LRS

echo "Create a serverless function app in the resource group."
az functionapp create \
  --name $functionAppName \
  --storage-account $storageName \
  --consumption-plan-location $region \
  --resource-group myResourceGroup \
  --os-type Linux \
  --runtime python \
  --runtime-version $pythonVersion \
  --functions-version 2

echo "Sleep 20 sec"
sleep 20

echo "Publish app"
func azure functionapp publish $functionAppName --build remote
